#Default config file for eukdetect. Copy and edit for analysis

#Directory where EukDetect output should be written
output_dir: "2021_gut_eukaryotes_in_IBD/Bioinformatic_pipeline/1000ibd_data/eukdetect/unrarefied_results"
  
#Indicate whether reads are paired (true) or single (false)
paired_end: true 

#filename excluding sample name. no need to edit if paired_end = false
fwd_suffix: "_1.fastq.gz" 

#filename excludign sample name. no need to edit if paired_end = false
rev_suffix: "_2.fastq.gz"

#file name excluding sample name. no need to edit if paired_end = true 
se_suffix: ".fastq.gz" 

#length of your reads. pre-trimming reads not recommended
readlen: 86

#full path to directory with raw fastq files
fq_dir: "2021_gut_eukaryotes_in_IBD/Bioinformatic_pipeline/1000ibd_data/kneaddata_output/decontaminated"

#full path to folder with eukdetect database files
database_dir: "2021_gut_eukaryotes_in_IBD/Bioinformatic_pipeline/tools/EukDetect-master/eukdetect_database_v1"

#name of database. Default is original genomes only database name
database_prefix: "all_buscos_v4.fna"

#full path to eukdetect installation folder
eukdetect_dir: "2021_gut_eukaryotes_in_IBD/Bioinformatic_pipeline/tools/EukDetect-master"

#list sample names here. fastqs must correspond to {samplename}{se_suffix} for SE reads or {samplename}{fwd_suffix} and {samplename}{rev_suffix} for PE
#each sample name should be preceded by 2 spaces and followed by a colon character
samples:
